### ISSUE TITLE
Simplify RigidAlignmentModule and GroupWiseRegistrationModule

### ISSUE THREAD

**Issue by jcfr** [NIRALUser/GROUPS#24]
When built against Slicer, the latest version of ShapePopulationViewer (SPV) is built as a loadable module.

This means that models already loaded in Slicer can easily be loaded in SPV, models can also be drag-and-dropped and loaded automatically.

This means that that the workflow in RigidAlignmentModule (or GroupWiseRegistrationModule) should be  updated.

Currently the workflow is expected to be the following:

1. Display shape in shape population viewer by starting the CLI and expect the user to select entries from the CSV dialog. See [here](https://github.com/NIRALUser/GROUPS/blob/15c897e611a09ec8746098883f409ea7daea5774/Modules/Scripted/RigidAlignmentModule/RigidAlignmentModule.py#L164-L188)
2. Run rigid alignment CLI (or GROUPS CLI)
3. Run surf remesh CLI
4. Display shape in shape population viewer by starting the CLI and expecting the user to select entries from the CSV dialog. See [here](https://github.com/NIRALUser/GROUPS/blob/15c897e611a09ec8746098883f409ea7daea5774/Modules/Scripted/RigidAlignmentModule/RigidAlignmentModule.py#L276-L298)

A possible workflow could be the following:

1. Run rigid alignment CLI (or GROUPS CLI)
2. Run surf remesh CLI
3. Automatically select SPV and load shapes (without creating intermediate CSV files)

**Comment by bpaniagua** [comment]
Thanks @jcfr 

@styner @juanprietob @mmmosman88 Could you please let us know what is the behavior you wanted and why in this module so we can decide how / if needs modification before including in SALT?


Thank you!
Bea

**Comment by jcfr** [comment]
Would also appreciate if you could review changes in https://github.com/NIRALUser/GROUPS/pull/25 and also provide test data for validating the workflow.

**Comment by juanprietob** [comment]
@bpaniagua The latter option is OK for me for the expected behavior
@jcfr the same dataset that is used for output of SPHARM can be used here.

**Comment by juanprietob** [comment]
This has all been addressed.
