### ISSUE TITLE
Re-fork repositories to avoid confusion

### ISSUE THREAD

**Issue by jcfr** [NIRALUser/GROUPS#27]
@ilwoolyu To avoid confusion, could you delete your project `ilwoolyu/GROUPS` and re-fork the one hosted in the `NIRALUser` organization. See https://github.com/NIRALUser/GROUPS

The fork graph currently shows this:

![image](https://user-images.githubusercontent.com/219043/70098770-fe428100-15fa-11ea-9121-fcccafd7d69c.png)

Thanks :pray:

**Comment by ilwoolyu** [comment]
Done.

**Comment by jcfr** [comment]
Thanks :+1:
