### ISSUE TITLE
Remove LAPACK dependency

### ISSUE THREAD

**Issue by Connor-Bowley** [NIRALUser/GROUPS#40]
It am unable to find where lapack is being used in this extension, and having LAPACK as a dependency is a bit of overhead with needing fortran and all.

**Comment by styner** [comment]
I don't think GROUPS is needing LAPACK (not 100% sure), this might be historically in there as the SPHARM-PDM extension needs LAPACK (and GROUPS usually follows SPHARM-PDM)

**Comment by sjh26** [comment]
SPHARM-PDM specifies its own LAPACK dependency, so it shouldn't be needed here as well.

**Comment by jcfr** [comment]
The `GroupwiseRegistration` explicitly requires the `ssyev_` lapack function `GroupwiseRegistration::eigenvalues` in the implementation of:


https://github.com/NIRALUser/GROUPS/blob/1263afc128b4ebf4442695af569d1832432e3d18/Modules/CLI/Groups/GroupwiseRegistration.cpp

Related links:
* https://netlib.org/lapack/explore-html/d3/d88/group__real_s_yeigen_ga63d8d12aef8f2711d711d9e6bd833e46.html
* https://github.com/Reference-LAPACK/lapack/blob/77a0ceb6c9a3c757e7039027f1f324e2811e6ee0/SRC/ssyev.f

**Comment by jcfr** [comment]
Use of `GroupwiseRegistration::eigenvalues` is the following:

```
GROUPS::main
  -> GroupwiseRegistration::run
    -> GroupwiseRegistration::optimization
      -> cost_function::operator()
        -> GroupwiseRegistration::cost
          -> GroupwiseRegistration::entropy
            -> GroupwiseRegistration::eigenvalues
              -> ssyev_
```

**Comment by jcfr** [comment]
Closing. This was addressed by @allemangD replacing LAPACK `ssyev` with Eigen `EigenSolver`
